image: node:12.18.1

pages:
  script:
  - yarn install
  - echo $GOOGLE_TAG_ID
  - ELEVENTY_ENV=production yarn build
  # The build directory is created based on the value set for projectName in
  # website/siteConfig.js. If you change it there, you need to change it here
  # as well.
  - mv ./_site ./public

  artifacts:
    paths:
    - public

  only:
  - master
